package(default_visibility = ["//visibility:public"])

load(
    "@com_github_mvukov_rules_ros2//ros2:cc_defs.bzl",
    "ros2_cpp_binary",
)

# Root-level validation or example targets
ros2_cpp_binary(
    name = "my_subscriber_node",
    srcs = [
        "src/my_component/my_subscriber.hpp",
        "src/my_component/my_subscriber.cpp",
    ],
    deps = [
        "@nav2_map_server//:map_io",
        "@ros2_rclcpp//:rclcpp",
        "@ros2_common_interfaces//:cpp_std_msgs",
    ],
)
